spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

logging:
  level:
    org.programming.microservice.apigateway: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.web: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
    instances:
      auth-service-circuit-breaker:
        baseConfig: default
      order-service-circuit-breaker:
        baseConfig: default
      product-service-circuit-breaker:
        baseConfig: default
      inventory-service-circuit-breaker:
        baseConfig: default
      cart-service-circuit-breaker:
        baseConfig: default