spring:
  application:
    name: cart-service
  data:
    redis:
      port: 6379
      connect-timeout: 5s
      host: localhost
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 9099

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            permittedNumberOfCallsInHalfOpenState: 3
            waitDurationInOpenState: 30s
            failureRateThreshold: 50